language: ruby
rvm:
  - 2.1.5
  - jruby-19mode
  - rbx-2.1.1
before_script:
  - cp config/database.example.yml config/database.yml
  - cp config/application.example.yml config/application.yml
  - bin/rake db:create db:migrate
  - bin/rake rubocop app spec lib
